#!/usr/bin/env bash

set -e

function __cleanup ()
{
	__delete_lock
}

function __create_lock ()
{
	if [[ -n ${lock_file} ]]
	then
		touch "${lock_file}"
	fi
}

function __delete_lock ()
{
	if [[ -e ${lock_file} ]]
	then
		rm -f "${lock_file}"
	fi
}

function __get_options ()
{
	local -r config_path="/etc/redis.conf"
	local -r options="${1:-"$(
		__get_redis_options
	)"}"

	printf -- \
		'%s%s%s' \
		"${config_path}" \
		"${options:+" "}" \
		"${options}"
}

function __get_redis_options ()
{
	printf -- '%s' "${REDIS_OPTIONS}"
}

function main ()
{
	local -r bin="/usr/bin/redis-server"
	local -r bootstrap_state_file="/var/lib/misc/redis-server-bootstrap"
	local -r bootstrap_timeout="4"
	local -r lock_file="/var/lock/redis/redis-server-wrapper"
	local -r nice="/bin/nice"
	local -r niceness="0"

	local options
	local verbose="false"

	while [[ "${#}" -gt 0 ]]
	do
		case "${1}" in
			-v|--verbose)
				verbose="true"
				shift 1
				;;
		esac
	done

	if [[ -e ${lock_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s lock detected - aborting\n' \
			"${0##*/}"
		exit 1
	fi

	trap __cleanup \
		EXIT INT TERM
	__create_lock

	options="$(
		__get_options
	)"

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
	fi

	set +e
	until [[ -f ${bootstrap_state_file} ]]
	do
		if ! inotifywait -qq \
			-e "create" \
			-t "${bootstrap_timeout}" \
			"${bootstrap_state_file%/*}"
		then
			break
		fi
	done
	set -e

	if ! [[ -f ${bootstrap_state_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s timed out waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
		exit 1
	fi

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s starting %s\n' \
			"${0##*/}" \
			"${bin##*/}"
	fi

	__cleanup
	trap - \
		EXIT INT TERM

	exec ${nice} \
		-n ${niceness} \
		${bin} \
		${options}
}

main "${@}"
